export const FETCH_QUIZZES_START = 'FETCH_QUIZZES_START'
export const FETCH_QUIZZES_SUCCESS = 'FETCH_QUIZZES_SUCCESS'
export const FETCH_QUIZZES_ERROR = 'FETCH_QUIZZES_ERROR'

export const FETCH_QUIZ_BY_ID_START = 'FETCH_QUIZ_BY_ID_START'
export const FETCH_QUIZ_BY_ID_SUCCESS = 'FETCH_QUIZ_BY_ID_SUCCESS'
export const FETCH_QUIZ_BY_ID_ERROR = 'FETCH_QUIZ_BY_ID_ERROR'

export const CLICK_RIGHT_ANSWER = 'CLICK_RIGHT_ANSWER'
export const IS_FINISHED_QUIZ = 'IS_FINISHED_QUIZ'
export const SET_NEXT_QUESTION = 'SET_NEXT_QUESTION'
export const SET_ANSWER_STATE_SUCCESS = 'SET_ANSWER_STATE_SUCCESS'
export const SET_ANSWER_STATE_ERROR = 'SET_ANSWER_STATE_ERROR'
export const SET_DEFAULT_STATE_CURRENT_QUIZ = 'SET_DEFAULT_STATE_CURRENT_QUIZ'